#
# Whenever a new tag starting with "v" is pushed, add the tagged version
# to the Moodle Plugins directory at https://moodle.org/plugins
#
# revision: 2021070201
#
name: Release to Moodle Plugins Directory

on:
  push:
    tags:
      - v*-stable

  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to be released'
        required: true

jobs:
  release:
    uses: Wunderbyte-GmbH/catalyst-moodle-workflows/.github/workflows/tag-release.yml@main
    with:
      plugin_name: local_shopping_cart
    secrets:
      moodle_org_token: ${{ secrets.MOODLE_ORG_TOKEN }}
